import pandas as pd
from datetime import datetime

class ReportGenerator:

    def generate_financial_report(
        self, ticker: str, company_info: dict, financial_data: dict, predictions: pd.DataFrame
    ) -> str:
        generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

        report = f"""# Financial Analysis Report: {ticker}
*Generated: {generated_at}*

---

## Company Overview

| Field        | Value |
|--------------|-------|
| Name         | {company_info.get("longName", "N/A")} |
| Sector       | {company_info.get("sector", "N/A")} |
| Industry     | {company_info.get("industry", "N/A")} |
| Market Cap   | {_fmt_currency(company_info.get("marketCap", 0))} |
| Current Price | ${_fmt_num(company_info.get("currentPrice", 0))} |

---

## Key Financial Metrics
"""
        metrics = financial_data.get("metrics", {})
        if metrics:
            report += f"""
| Metric              | Value |
|---------------------|-------|
| P/E Ratio           | {_fmt_metric(metrics.get("peRatio"))} |
| P/B Ratio           | {_fmt_metric(metrics.get("priceToBook"))} |
| Debt-to-Equity      | {_fmt_metric(metrics.get("debtToEquity"))} |
| Return on Equity    | {_fmt_pct(metrics.get("returnOnEquity"))} |
| Profit Margin       | {_fmt_pct(metrics.get("profitMargins"))} |
"""
        else:
            report += "\n*Financial metrics unavailable.*\n"

        if predictions is not None and not predictions.empty:
            ensemble_col = "ensemble" if "ensemble" in predictions.columns else predictions.columns[0]
            
            # Count how many UP days are predicted
            up_days = (predictions[ensemble_col] == "UP").sum()
            total_days = len(predictions)
            up_pct = (up_days / total_days) * 100

            report += f"""
---

## Trading Signal Forecast ({total_days}-day outlook)

| Metric | Prediction |
|---|---|
| Forecast window | {total_days} days |
| Predicted 'UP' days | {up_days} ({up_pct:.1f}%) |
| Predicted 'DOWN' days | {total_days - up_days} |

### Next-Day Model Consensus
| Model | Next Day Signal |
|-------|-----------------|
"""
            day1 = predictions.iloc[0]
            for col in predictions.columns:
                if col != "ensemble":
                    report += f"| {col.upper():10s} | **{day1[col]}** |\n"
            report += f"| **Ensemble** | **{day1['ensemble']}** |\n\n### Recommendation\n"

            if up_pct >= 60:
                signal = "**STRONG BUY** — Models project consistent upward momentum."
            elif up_pct > 50:
                signal = "**MILD BUY** — Models project slight upward momentum."
            elif up_pct <= 40:
                signal = "**STRONG SELL** — Models project consistent downward momentum."
            else:
                signal = "**HOLD / UNCERTAIN** — Models project mixed signals or downward bias."

            report += f"{signal}\n"
        else:
            report += "\n*Forecast data unavailable.*\n"

        report += """
---
## Disclaimer
> This report is generated by an automated machine-learning system and is
> provided for **informational purposes only**.
"""
        return report

def _fmt_num(value, decimals: int = 2) -> str:
    if value is None: return "N/A"
    try: return f"{float(value):,.{decimals}f}"
    except: return "N/A"

def _fmt_currency(value) -> str:
    if not value: return "N/A"
    try:
        v = float(value)
        if v >= 1e12: return f"${v/1e12:.2f}T"
        if v >= 1e9: return f"${v/1e9:.2f}B"
        if v >= 1e6: return f"${v/1e6:.2f}M"
        return f"${v:,.0f}"
    except: return "N/A"

def _fmt_metric(value) -> str:
    if value is None or value == "N/A": return "N/A"
    try: return f"{float(value):.2f}"
    except: return str(value)

def _fmt_pct(value) -> str:
    if value is None or value == "N/A": return "N/A"
    try: return f"{float(value):.2f}%"
    except: return str(value)